services:
  - type: web
    name: narrative-ai-detector
    env: python
    plan: standard  # Use standard plan to get more memory
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn --workers 1 --threads 2 -b 0.0.0.0:10000 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DISCORD_TOKEN
        sync: false
      - key: LOGS_CHANNEL_ID
        sync: false
      - key: MONITORED_CATEGORY_IDS
        sync: false
      - key: ALERT_THRESHOLD
        value: 70
      - key: MIN_CHARS
        value: 100
      - key: HEARTBEAT_INTERVAL
        value: 300
      - key: WEB_CONCURRENCY
        value: 1
    healthCheckPath: /health
    autoDeploy: true